import React from 'react';
import { AbsoluteFill, useVideoConfig, useCurrentFrame, interpolate, spring } from 'remotion';

export const AiDynamicPromo = ({ 
  title = "Your Prompt Here", 
  subtitle = "Generated by Jomocal AI",
  brandColor = "#3b82f6",
  accentColor = "#10b981",
  elements = [],
  animationStyle = "fluid" 
}) => {
  const frame = useCurrentFrame();
  const { fps, width, height } = useVideoConfig();

  // Entrance animations
  const titleSpring = spring({ frame, fps, delay: 10, config: { damping: 12 } });
  const subtitleSpring = spring({ frame, fps, delay: 25, config: { damping: 10 } });

  return (
    <AbsoluteFill style={{ 
      backgroundColor: '#0a0a0a',
      background: `radial-gradient(circle at 50% 50%, ${brandColor}22 0%, #000 70%)`,
      color: 'white',
      fontFamily: 'Inter, system-ui, sans-serif'
    }}>
      {/* Dynamic Elements / Particles */}
      {elements.map((el, i) => {
        const moveX = interpolate(frame, [0, 300], [el.startX || 0, el.endX || width], { extrapolateRight: 'clamp' });
        const moveY = interpolate(frame, [0, 300], [el.startY || 0, el.endY || height], { extrapolateRight: 'clamp' });
        const rotate = interpolate(frame, [0, 300], [0, el.rotation || 360]);
        const opacity = interpolate(frame, [0, 20, 280, 300], [0, el.opacity || 1, el.opacity || 1, 0]);

        return (
          <div
            key={i}
            style={{
              position: 'absolute',
              left: moveX,
              top: moveY,
              width: el.size || 50,
              height: el.size || 50,
              backgroundColor: el.color || accentColor,
              borderRadius: el.type === 'circle' ? '50%' : '12px',
              opacity,
              transform: `rotate(${rotate}deg) scale(${spring({ frame, fps, delay: i * 5, config: { stiffness: 100 } })})`,
              boxShadow: `0 0 20px ${el.color || accentColor}44`,
              border: `2px solid ${el.color || accentColor}88`
            }}
          />
        );
      })}

      {/* Text Content */}
      <div style={{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100%',
        padding: '0 100px',
        textAlign: 'center'
      }}>
        <h1 style={{
          fontSize: 120,
          fontWeight: 900,
          marginBottom: 20,
          color: 'white',
          textShadow: `0 0 40px ${brandColor}66`,
          transform: `scale(${titleSpring}) translateY(${interpolate(titleSpring, [0, 1], [50, 0])}px)`,
          opacity: titleSpring
        }}>
          {title}
        </h1>
        <p style={{
          fontSize: 48,
          fontWeight: 500,
          color: '#94a3b8',
          letterSpacing: '2px',
          textTransform: 'uppercase',
          transform: `translateY(${interpolate(subtitleSpring, [0, 1], [30, 0])}px)`,
          opacity: subtitleSpring
        }}>
          {subtitle}
        </p>
      </div>

      {/* Decorative Border */}
      <div style={{
        position: 'absolute',
        inset: 40,
        border: `1px solid ${brandColor}44`,
        borderRadius: 40,
        pointerEvents: 'none'
      }} />
      
      {/* Brand Watermark */}
      <div style={{
        position: 'absolute',
        bottom: 60,
        right: 80,
        fontSize: 32,
        fontWeight: 'bold',
        color: `${accentColor}88`,
        opacity: 0.5
      }}>
        JOMOCAL AI
      </div>
    </AbsoluteFill>
  );
};
